// <auto-generated />
using System;
using ApiPB101.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPB101.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiPB101.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "yazici1",
                            CreatedDate = new DateTime(2024, 6, 12, 21, 58, 2, 825, DateTimeKind.Local).AddTicks(9844),
                            Name = "Kitab1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "yazici2",
                            CreatedDate = new DateTime(2024, 6, 12, 21, 58, 2, 825, DateTimeKind.Local).AddTicks(9847),
                            Name = "Kitab2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "yazici3",
                            CreatedDate = new DateTime(2024, 6, 12, 21, 58, 2, 825, DateTimeKind.Local).AddTicks(9848),
                            Name = "Kitab3"
                        });
                });

            modelBuilder.Entity("ApiPB101.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 12, 21, 58, 2, 825, DateTimeKind.Local).AddTicks(9650),
                            Name = "UI UX"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 12, 21, 58, 2, 825, DateTimeKind.Local).AddTicks(9691),
                            Name = "UI"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 12, 21, 58, 2, 825, DateTimeKind.Local).AddTicks(9693),
                            Name = "UX"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
